# Generated by Django 4.2.7 on 2026-04-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("page_view", "Page View"),
                            ("cta_click", "CTA Click"),
                            ("form_submit", "Form Submit"),
                            ("portfolio_view", "Portfolio View"),
                            ("service_view", "Service View"),
                        ],
                        max_length=100,
                    ),
                ),
                ("page_url", models.CharField(blank=True, max_length=500)),
                ("user_session_id", models.CharField(blank=True, max_length=255)),
                ("event_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Analytics Event",
                "verbose_name_plural": "Analytics Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="analytics_a_event_t_002468_idx",
                    ),
                    models.Index(
                        fields=["user_session_id", "-created_at"],
                        name="analytics_a_user_se_beb4f6_idx",
                    ),
                ],
            },
        ),
    ]
