# Generated by Django 4.2.7 on 2026-04-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="user_session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
