# Generated by Django 4.2.7 on 2026-04-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("client_name", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("graphics", "Graphics"),
                            ("social_media", "Social Media"),
                            ("video", "Video"),
                            ("ads", "Ads"),
                            ("websites", "Websites"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("featured_image", models.ImageField(upload_to="portfolio/")),
                ("gallery_images", models.JSONField(blank=True, default=list)),
                ("videos", models.JSONField(blank=True, default=list)),
                ("timeline", models.CharField(blank=True, max_length=100)),
                ("results", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "services_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="portfolio_projects",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Project",
                "verbose_name_plural": "Portfolio Projects",
                "ordering": ["-order", "-created_at"],
            },
        ),
    ]
