# Generated by Django 4.2.7 on 2026-09-09 01:23

from urllib.parse import urlparse

from django.db import migrations, models
import django.db.models.deletion


def stored_media_name(value):
    text = str(value or "").strip()
    if not text:
        return ""
    if text.startswith(("http://", "https://")):
        parsed = urlparse(text)
        parts = [part for part in parsed.path.split("/") if part]
        host = (parsed.netloc or "").lower()
        if host in ("storage.googleapis.com", "storage.cloud.google.com") and len(parts) > 1:
            return "/".join(parts[1:])
        return "/".join(parts)
    return text.lstrip("/")


def is_embed_url(value):
    host = urlparse(str(value or "").strip()).netloc.lower()
    return any(part in host for part in ("youtube.com", "youtu.be", "vimeo.com"))


def copy_json_media(apps, schema_editor):
    PortfolioProject = apps.get_model("portfolio", "PortfolioProject")
    PortfolioGalleryImage = apps.get_model("portfolio", "PortfolioGalleryImage")
    PortfolioVideo = apps.get_model("portfolio", "PortfolioVideo")

    for project in PortfolioProject.objects.all():
        for index, raw in enumerate(project.gallery_images or []):
            name = stored_media_name(raw)
            if not name:
                continue
            item = PortfolioGalleryImage(project=project, caption="", order=index)
            item.image.name = name
            item.save()

        for index, raw in enumerate(project.videos or []):
            text = str(raw or "").strip()
            if not text:
                continue
            video = PortfolioVideo(project=project, order=index)
            if is_embed_url(text):
                video.embed_url = text[:200]
            else:
                name = stored_media_name(text)
                if not name:
                    continue
                video.video.name = name
            video.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("video", models.FileField(blank=True, upload_to="portfolio/videos/")),
                (
                    "embed_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube or Vimeo link if you are not uploading a file.",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_items",
                        to="portfolio.portfolioproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery video",
                "verbose_name_plural": "Gallery videos",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioGalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="portfolio/gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="portfolio.portfolioproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gallery image",
                "verbose_name_plural": "Gallery images",
                "ordering": ["order", "id"],
            },
        ),
        migrations.RunPython(copy_json_media, noop),
        migrations.RemoveField(
            model_name="portfolioproject",
            name="gallery_images",
        ),
        migrations.RemoveField(
            model_name="portfolioproject",
            name="videos",
        ),
    ]
